### ISSUE TITLE
cropperjs: module not found

### ISSUE THREAD

**Issue by mrkvon** [ogix/ng2-fancy-image-uploader#1]
Hello, trying to use ng2-fancy-image-uploader with angular-cli (webpack), i ran into the following error:

```
ERROR in ./~/ng2-fancy-image-uploader/dist/src/fancy-image-uploader.component.js
Module not found: Error: Can't resolve 'cropperjs' in '/home/[path-to-angular-cli-project]/node_modules/ng2-fancy-image-uploader/dist/src'
 @ ./~/ng2-fancy-image-uploader/dist/src/fancy-image-uploader.component.js 7:18-38
 @ ./~/ng2-fancy-image-uploader/dist/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://dev.ditup.org:4200 ./src/main.ts
```

Tried to resolve it with `npm install cropperjs`, but that doesn't help.

**Comment by uiuxdeveloper** [comment]
same issue here

**Comment by ogix** [comment]
Hello, I have already fixed this issue but haven't published a new version yet. Will publish later today.

**Comment by ogix** [comment]
Can you confirm that it works now so I could close the issue?

**Comment by mrkvon** [comment]
@ogix 
Yes, i confirm. Now, my angular-cli project compiles without error and the `ng2-fancy-image-uploader` works in basic version.

**Comment by ogix** [comment]
Thanks. I will update demo later with cropping function.

**Comment by haifzhan** [comment]
I am using version 1.5.1 but still get the issue:
```
node_modules/ng2-fancy-image-uploader/dist/src/fancy-image-uploader.component.d.ts (1,1): Cannot find type definition file for 'cropperjs'.
webpack: Failed to compile.
```

Please help, thanks!

**Comment by ogix** [comment]
Released a new version. Please check if you still have this issue
